name: Reusable workflow Trigger Jenkins Repository Scan

on:
    workflow_call:
        inputs:
            project-name:
                required: true
                type: string
            project-organization:
                required: true
                type: string
jobs:
    trigger-repo-scan:
        runs-on: self-hosted

        steps:
        - name: Display Variables
          id: vars
          run: |
            echo "Project name : ${{ inputs.project-name }}"
            echo "Project organization : ${{ inputs.project-organization }}"

        - name: Construct Curl Command
          run: |
            curl_command="curl -k -X POST \"https://jenkins-test.mbt.lab.etn.com/job/IPM2/job/TRIGGER_PIPELINES/job/TRIGGER_REPO_SCAN/buildWithParameters\" \
            --user \"${{ secrets.GHE_TRIGGER_JENKINS_USER }}:${{ secrets.GHE_TRIGGER_JENKINS_TOKEN }}\" \
            --data-urlencode \"PROJECT_NAME=${{ inputs.project-name }}\" \
            --data-urlencode \"PROJECT_ORGANIZATION=${{ inputs.project-organization }}\""

         
            echo $curl_command > curl_command.sh
        - name: Trigger Scan Repository
          run: |
                cat curl_command.sh
                sh curl_command.sh